apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    pod: myapp
spec:
  containers:
  - image: nginx
    name: nginx 
  - image: redis 
    name: redis
  - image: memcached
    name: memcached
  - image: consul
    name: consul 

