kind: Namespace
apiVersion: v1
metadata:
  name: web



---
apiVersion: v1
kind: Pod
metadata:
  name: redis1
  namespace: web
spec:
  containers:
  - name: redis2
    image: redis
    ports:
    - containerPort: 9090
